services:
  - type: web
    name: coin-monitor
    env: ruby
    plan: free
    buildCommand: |
      bundle install
      mkdir -p public/assets
      mkdir -p tmp/cache
      bundle exec rails assets:precompile || echo "Assets precompilation failed, continuing..."
      bundle exec rails db:migrate
    startCommand: bundle exec rails server
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: coin-monitor-db
          property: connectionString
      - key: SECRET_KEY_BASE
        value: 7c28b991c1cdd601d4df5e973fba4d50ba0b20a056982c63ea068d55f76c8ed9d2fa54001228e114e0af3f4bba32db1d16be68835753c36993d6a08b1b2e8886

databases:
  - name: coin-monitor-db
    databaseName: coin_monitor_production
    user: coin_monitor_user
    plan: free
